/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-06-30 03:38:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


response.setHeader(
"Cache-Control",
"no-cache, no-store, must-revalidate");

response.setHeader(
"Pragma",
"no-cache");

response.setDateHeader(
"Expires", 0);

if(session.getAttribute("user") == null){

    response.sendRedirect(
    "login.jsp");

    return;
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Hospital Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\"\r\n");
      out.write("href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\"\r\n");
      out.write("href=\"https://fonts.gstatic.com\"\r\n");
      out.write("crossorigin>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".reminder-item{\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("padding:14px;\r\n");
      out.write("\r\n");
      out.write("border-radius:16px;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.05);\r\n");
      out.write("\r\n");
      out.write("margin-bottom:15px;\r\n");
      out.write("\r\n");
      out.write("transition:0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reminder-item:hover{\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("transform:\r\n");
      out.write("translateX(5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reminder-dot{\r\n");
      out.write("\r\n");
      out.write("width:12px;\r\n");
      out.write("\r\n");
      out.write("height:12px;\r\n");
      out.write("\r\n");
      out.write("border-radius:50%;\r\n");
      out.write("\r\n");
      out.write("background:#4ade80;\r\n");
      out.write("\r\n");
      out.write("margin-right:15px;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 0 12px #4ade80;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reminder-text{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("font-size:15px;\r\n");
      out.write("\r\n");
      out.write("font-weight:500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".empty-reminder{\r\n");
      out.write("\r\n");
      out.write("color:#cbd5e1;\r\n");
      out.write("\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("    <!-- TITLE -->\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"dashboard-title\">\r\n");
      out.write("\r\n");
      out.write("        Hospital Management Dashboard\r\n");
      out.write("\r\n");
      out.write("    </h1>\r\n");
      out.write("\r\n");
      out.write("    <!-- STATS -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4 mb-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card stat-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-icon\">\r\n");
      out.write("\r\n");
      out.write("                    <i class=\"bi bi-people-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-title\">\r\n");
      out.write("\r\n");
      out.write("                    Total Patients\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-value\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( request.getAttribute("patientCount") != null
                    ? request.getAttribute("patientCount")
                    : 0 );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card stat-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-icon\">\r\n");
      out.write("\r\n");
      out.write("                    <i class=\"bi bi-person-badge-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-title\">\r\n");
      out.write("\r\n");
      out.write("                    Total Doctors\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-value\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( request.getAttribute("doctorCount") != null
                    ? request.getAttribute("doctorCount")
                    : 0 );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card stat-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-icon\">\r\n");
      out.write("\r\n");
      out.write("                    <i class=\"bi bi-calendar-check-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-title\">\r\n");
      out.write("\r\n");
      out.write("                    Appointments\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-value\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( request.getAttribute("appointmentCount") != null
                    ? request.getAttribute("appointmentCount")
                    : 0 );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card stat-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-icon\">\r\n");
      out.write("\r\n");
      out.write("                    <i class=\"bi bi-receipt-cutoff\"></i>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-title\">\r\n");
      out.write("\r\n");
      out.write("                    Bills\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"stat-value\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( request.getAttribute("billCount") != null
                    ? request.getAttribute("billCount")
                    : 0 );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- QUICK ACTIONS -->\r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"section-title\">\r\n");
      out.write("\r\n");
      out.write("        Quick Actions\r\n");
      out.write("\r\n");
      out.write("    </h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4 mb-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card action-card\">\r\n");
      out.write("\r\n");
      out.write("                <h3>Appointments</h3>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("\r\n");
      out.write("                    Book and manage appointments.\r\n");
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"appointment.jsp\"\r\n");
      out.write("                   class=\"btn btn-primary modern-btn\">\r\n");
      out.write("\r\n");
      out.write("                   Open Module\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card action-card\">\r\n");
      out.write("\r\n");
      out.write("                <h3>Patients</h3>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("\r\n");
      out.write("                    Manage patient records.\r\n");
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"patientRegister.jsp\"\r\n");
      out.write("                   class=\"btn btn-success modern-btn\">\r\n");
      out.write("\r\n");
      out.write("                   Open Module\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"glass-card action-card\">\r\n");
      out.write("\r\n");
      out.write("                <h3>Doctors</h3>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("\r\n");
      out.write("                    Manage doctor information.\r\n");
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"doctorRegister.jsp\"\r\n");
      out.write("                   class=\"btn btn-warning modern-btn\">\r\n");
      out.write("\r\n");
      out.write("                   Open Module\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- APPOINTMENT REMINDERS -->\r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"section-title\">\r\n");
      out.write("\r\n");
      out.write("        Today's Appointment Reminders\r\n");
      out.write("\r\n");
      out.write("    </h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"glass-card mb-5\">\r\n");
      out.write("\r\n");


ArrayList<String> reminders =

(ArrayList<String>)
request.getAttribute(
"reminders");

if(reminders != null
   && !reminders.isEmpty()){

for(String reminder : reminders){


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"reminder-item\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"reminder-dot\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"reminder-text\">\r\n");
      out.write("\r\n");
      out.write("        ");
      out.print( reminder );
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");


}

}else{


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"empty-reminder\">\r\n");
      out.write("\r\n");
      out.write("    No appointments scheduled today.\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");


}


      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ANALYTICS -->\r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"section-title\">\r\n");
      out.write("\r\n");
      out.write("        Hospital Analytics\r\n");
      out.write("\r\n");
      out.write("    </h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"glass-card chart-card\">\r\n");
      out.write("\r\n");
      out.write("        <canvas id=\"hospitalChart\"></canvas>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- FLOATING SHORTCUTS -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"floating-widgets\">\r\n");
      out.write("\r\n");
      out.write("    <a href=\"patientRegister.jsp\"\r\n");
      out.write("       class=\"floating-widget\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-people-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"appointment.jsp\"\r\n");
      out.write("       class=\"floating-widget\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-calendar-check-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"aiAssistant.jsp\"\r\n");
      out.write("       class=\"floating-widget\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-cpu-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"labReport.jsp\"\r\n");
      out.write("       class=\"floating-widget emergency-widget\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-file-earmark-medical-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("const ctx =\r\n");
      out.write("document.getElementById(\r\n");
      out.write("'hospitalChart');\r\n");
      out.write("\r\n");
      out.write("new Chart(ctx, {\r\n");
      out.write("\r\n");
      out.write("type:'bar',\r\n");
      out.write("\r\n");
      out.write("data:{\r\n");
      out.write("\r\n");
      out.write("labels:[\r\n");
      out.write("\r\n");
      out.write("'Patients',\r\n");
      out.write("'Doctors',\r\n");
      out.write("'Appointments',\r\n");
      out.write("'Bills'\r\n");
      out.write("\r\n");
      out.write("],\r\n");
      out.write("\r\n");
      out.write("datasets:[{\r\n");
      out.write("\r\n");
      out.write("label:'Hospital Statistics',\r\n");
      out.write("\r\n");
      out.write("data:[\r\n");
      out.write("\r\n");
      out.print( request.getAttribute("patientCount") != null ? request.getAttribute("patientCount") : 0 );
      out.write(",\r\n");
      out.write("\r\n");
      out.print( request.getAttribute("doctorCount") != null ? request.getAttribute("doctorCount") : 0 );
      out.write(",\r\n");
      out.write("\r\n");
      out.print( request.getAttribute("appointmentCount") != null ? request.getAttribute("appointmentCount") : 0 );
      out.write(",\r\n");
      out.write("\r\n");
      out.print( request.getAttribute("billCount") != null ? request.getAttribute("billCount") : 0 );
      out.write("\r\n");
      out.write("\r\n");
      out.write("],\r\n");
      out.write("\r\n");
      out.write("borderRadius:12\r\n");
      out.write("\r\n");
      out.write("}]\r\n");
      out.write("\r\n");
      out.write("},\r\n");
      out.write("\r\n");
      out.write("options:{\r\n");
      out.write("\r\n");
      out.write("responsive:true,\r\n");
      out.write("\r\n");
      out.write("plugins:{\r\n");
      out.write("\r\n");
      out.write("legend:{\r\n");
      out.write("\r\n");
      out.write("labels:{\r\n");
      out.write("\r\n");
      out.write("color:'white'\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("},\r\n");
      out.write("\r\n");
      out.write("scales:{\r\n");
      out.write("\r\n");
      out.write("x:{\r\n");
      out.write("\r\n");
      out.write("ticks:{\r\n");
      out.write("\r\n");
      out.write("color:'white'\r\n");
      out.write("\r\n");
      out.write("},\r\n");
      out.write("\r\n");
      out.write("grid:{\r\n");
      out.write("\r\n");
      out.write("color:'rgba(255,255,255,0.08)'\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("},\r\n");
      out.write("\r\n");
      out.write("y:{\r\n");
      out.write("\r\n");
      out.write("ticks:{\r\n");
      out.write("\r\n");
      out.write("color:'white'\r\n");
      out.write("\r\n");
      out.write("},\r\n");
      out.write("\r\n");
      out.write("grid:{\r\n");
      out.write("\r\n");
      out.write("color:'rgba(255,255,255,0.08)'\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
