/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-06-30 03:38:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Patient Registration</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\"\r\n");
      out.write("href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\"\r\n");
      out.write("href=\"https://fonts.gstatic.com\"\r\n");
      out.write("crossorigin>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".register-wrapper{\r\n");
      out.write("\r\n");
      out.write("min-height:100vh;\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("justify-content:center;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("padding:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-card{\r\n");
      out.write("\r\n");
      out.write("width:100%;\r\n");
      out.write("\r\n");
      out.write("max-width:520px;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.06);\r\n");
      out.write("\r\n");
      out.write("backdrop-filter:blur(22px);\r\n");
      out.write("\r\n");
      out.write("border:\r\n");
      out.write("1px solid rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("border-radius:30px;\r\n");
      out.write("\r\n");
      out.write("padding:40px;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 10px 40px rgba(0,0,0,0.45);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("\r\n");
      out.write("font-size:34px;\r\n");
      out.write("\r\n");
      out.write("font-weight:700;\r\n");
      out.write("\r\n");
      out.write("text-align:center;\r\n");
      out.write("\r\n");
      out.write("margin-bottom:10px;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subtitle{\r\n");
      out.write("\r\n");
      out.write("text-align:center;\r\n");
      out.write("\r\n");
      out.write("color:#cbd5e1;\r\n");
      out.write("\r\n");
      out.write("margin-bottom:35px;\r\n");
      out.write("\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-btn{\r\n");
      out.write("\r\n");
      out.write("width:100%;\r\n");
      out.write("\r\n");
      out.write("padding:15px;\r\n");
      out.write("\r\n");
      out.write("border:none;\r\n");
      out.write("\r\n");
      out.write("border-radius:18px;\r\n");
      out.write("\r\n");
      out.write("font-size:16px;\r\n");
      out.write("\r\n");
      out.write("font-weight:600;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("linear-gradient(\r\n");
      out.write("135deg,\r\n");
      out.write("#7c3aed,\r\n");
      out.write("#4f46e5,\r\n");
      out.write("#2563eb\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("transition:0.3s ease;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 10px 25px rgba(79,70,229,0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-btn:hover{\r\n");
      out.write("\r\n");
      out.write("transform:\r\n");
      out.write("translateY(-3px);\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 15px 35px rgba(79,70,229,0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-link{\r\n");
      out.write("\r\n");
      out.write("text-align:center;\r\n");
      out.write("\r\n");
      out.write("margin-top:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-link a{\r\n");
      out.write("\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("\r\n");
      out.write("font-size:15px;\r\n");
      out.write("\r\n");
      out.write("font-weight:500;\r\n");
      out.write("\r\n");
      out.write("color:#a78bfa;\r\n");
      out.write("\r\n");
      out.write("transition:0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-link a:hover{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"register-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"register-card\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("\r\n");
      out.write("            Patient Registration\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"subtitle\">\r\n");
      out.write("\r\n");
      out.write("            Create patient HMS profile\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"PatientServlet\"\r\n");
      out.write("      method=\"post\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\"\r\n");
      out.write("                       name=\"patientName\"\r\n");
      out.write("                       class=\"form-control\"\r\n");
      out.write("                       placeholder=\"Patient Name\"\r\n");
      out.write("                       required>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"number\"\r\n");
      out.write("                       name=\"age\"\r\n");
      out.write("                       class=\"form-control\"\r\n");
      out.write("                       placeholder=\"Age\"\r\n");
      out.write("                       required>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("\r\n");
      out.write("                <select name=\"gender\"\r\n");
      out.write("                        class=\"form-control custom-select\"\r\n");
      out.write("                        required>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"\">\r\n");
      out.write("\r\n");
      out.write("                        Select Gender\r\n");
      out.write("\r\n");
      out.write("                    </option>\r\n");
      out.write("\r\n");
      out.write("                    <option>\r\n");
      out.write("\r\n");
      out.write("                        Male\r\n");
      out.write("\r\n");
      out.write("                    </option>\r\n");
      out.write("\r\n");
      out.write("                    <option>\r\n");
      out.write("\r\n");
      out.write("                        Female\r\n");
      out.write("\r\n");
      out.write("                    </option>\r\n");
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\"\r\n");
      out.write("                       name=\"disease\"\r\n");
      out.write("                       class=\"form-control\"\r\n");
      out.write("                       placeholder=\"Disease / Condition\"\r\n");
      out.write("                       required>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\"\r\n");
      out.write("                       name=\"phone\"\r\n");
      out.write("                       class=\"form-control\"\r\n");
      out.write("                       placeholder=\"Phone Number\"\r\n");
      out.write("                       required>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\"\r\n");
      out.write("                    class=\"register-btn\">\r\n");
      out.write("\r\n");
      out.write("                Register Patient\r\n");
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"back-link\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"dashboard.jsp\">\r\n");
      out.write("\r\n");
      out.write("                Back\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
