/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-06-30 03:38:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".sidebar{\r\n");
      out.write("\r\n");
      out.write("position:fixed;\r\n");
      out.write("\r\n");
      out.write("top:20px;\r\n");
      out.write("\r\n");
      out.write("left:20px;\r\n");
      out.write("\r\n");
      out.write("width:240px;\r\n");
      out.write("\r\n");
      out.write("height:95vh;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("backdrop-filter:blur(20px);\r\n");
      out.write("\r\n");
      out.write("border:1px solid rgba(255,255,255,0.1);\r\n");
      out.write("\r\n");
      out.write("border-radius:30px;\r\n");
      out.write("\r\n");
      out.write("padding:25px;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 8px 32px rgba(0,0,0,0.35);\r\n");
      out.write("\r\n");
      out.write("z-index:1000;\r\n");
      out.write("\r\n");
      out.write("overflow-y:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo{\r\n");
      out.write("\r\n");
      out.write("font-size:28px;\r\n");
      out.write("\r\n");
      out.write("font-weight:700;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("margin-bottom:40px;\r\n");
      out.write("\r\n");
      out.write("text-align:center;\r\n");
      out.write("\r\n");
      out.write("letter-spacing:1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link-custom{\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("gap:14px;\r\n");
      out.write("\r\n");
      out.write("padding:14px 18px;\r\n");
      out.write("\r\n");
      out.write("margin-bottom:14px;\r\n");
      out.write("\r\n");
      out.write("border-radius:18px;\r\n");
      out.write("\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("font-weight:500;\r\n");
      out.write("\r\n");
      out.write("transition:0.3s ease;\r\n");
      out.write("\r\n");
      out.write("font-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link-custom:hover{\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.12);\r\n");
      out.write("\r\n");
      out.write("transform:\r\n");
      out.write("translateX(8px);\r\n");
      out.write("\r\n");
      out.write("color:#8b5cf6;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 0 20px rgba(139,92,246,0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link-custom i{\r\n");
      out.write("\r\n");
      out.write("font-size:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-btn{\r\n");
      out.write("\r\n");
      out.write("margin-top:25px;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("linear-gradient(\r\n");
      out.write("135deg,\r\n");
      out.write("#ef4444,\r\n");
      out.write("#dc2626\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("justify-content:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-btn:hover{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar::-webkit-scrollbar{\r\n");
      out.write("\r\n");
      out.write("width:6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar::-webkit-scrollbar-thumb{\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.15);\r\n");
      out.write("\r\n");
      out.write("border-radius:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("        HMS\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"DashboardServlet\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-grid-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       Dashboard\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"patientRegister.jsp\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-people-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       Add Patient\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"doctorRegister.jsp\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-person-badge-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       Add Doctor\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"GetAppointmentsServlet\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-calendar-check-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       Appointments\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"labReport.jsp\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-file-earmark-medical-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       Lab Reports\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"GetMedicinesServlet\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-capsule-pill\"></i>\r\n");
      out.write("\r\n");
      out.write("       Pharmacy\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"GetPatientsServlet\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-person-lines-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       View Patients\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"GetDoctorsServlet\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-hospital-fill\"></i>\r\n");
      out.write("\r\n");
      out.write("       View Doctors\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"GetAppointmentsServlet\"\r\n");
      out.write("       class=\"nav-link-custom\">\r\n");
      out.write("\r\n");
      out.write("       <i class=\"bi bi-journal-medical\"></i>\r\n");
      out.write("\r\n");
      out.write("       View Appointments\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
