/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-06-30 03:38:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".search-container{\r\n");
      out.write("\r\n");
      out.write("position:relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".suggestions-box{\r\n");
      out.write("\r\n");
      out.write("position:absolute;\r\n");
      out.write("\r\n");
      out.write("top:55px;\r\n");
      out.write("\r\n");
      out.write("left:0;\r\n");
      out.write("\r\n");
      out.write("width:100%;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(15,23,42,0.95);\r\n");
      out.write("\r\n");
      out.write("border:\r\n");
      out.write("1px solid rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("border-radius:16px;\r\n");
      out.write("\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("\r\n");
      out.write("backdrop-filter:blur(15px);\r\n");
      out.write("\r\n");
      out.write("display:none;\r\n");
      out.write("\r\n");
      out.write("z-index:9999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".suggestion-item{\r\n");
      out.write("\r\n");
      out.write("padding:12px 16px;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("\r\n");
      out.write("transition:0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".suggestion-item:hover{\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(139,92,246,0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbar{\r\n");
      out.write("\r\n");
      out.write("position:fixed;\r\n");
      out.write("\r\n");
      out.write("top:20px;\r\n");
      out.write("\r\n");
      out.write("left:280px;\r\n");
      out.write("\r\n");
      out.write("right:20px;\r\n");
      out.write("\r\n");
      out.write("height:80px;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("backdrop-filter:blur(20px);\r\n");
      out.write("\r\n");
      out.write("border:\r\n");
      out.write("1px solid rgba(255,255,255,0.1);\r\n");
      out.write("\r\n");
      out.write("border-radius:25px;\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("justify-content:space-between;\r\n");
      out.write("\r\n");
      out.write("padding:0 30px;\r\n");
      out.write("\r\n");
      out.write("z-index:999;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 8px 32px rgba(0,0,0,0.35);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box{\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("border:none;\r\n");
      out.write("\r\n");
      out.write("outline:none;\r\n");
      out.write("\r\n");
      out.write("padding:12px 18px;\r\n");
      out.write("\r\n");
      out.write("border-radius:14px;\r\n");
      out.write("\r\n");
      out.write("width:280px;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("font-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box::placeholder{\r\n");
      out.write("\r\n");
      out.write("color:\r\n");
      out.write("rgba(255,255,255,0.7);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-section{\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("gap:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-profile{\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("gap:10px;\r\n");
      out.write("\r\n");
      out.write("font-weight:600;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-profile i{\r\n");
      out.write("\r\n");
      out.write("font-size:26px;\r\n");
      out.write("\r\n");
      out.write("color:#a78bfa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-link{\r\n");
      out.write("\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("\r\n");
      out.write("padding:10px 18px;\r\n");
      out.write("\r\n");
      out.write("border-radius:14px;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(239,68,68,0.18);\r\n");
      out.write("\r\n");
      out.write("color:#f87171;\r\n");
      out.write("\r\n");
      out.write("font-weight:600;\r\n");
      out.write("\r\n");
      out.write("transition:0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-link:hover{\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("rgba(239,68,68,0.3);\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-section{\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("gap:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clock{\r\n");
      out.write("\r\n");
      out.write("font-size:18px;\r\n");
      out.write("\r\n");
      out.write("font-weight:500;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-circle{\r\n");
      out.write("\r\n");
      out.write("width:48px;\r\n");
      out.write("\r\n");
      out.write("height:48px;\r\n");
      out.write("\r\n");
      out.write("border-radius:50%;\r\n");
      out.write("\r\n");
      out.write("background:\r\n");
      out.write("linear-gradient(\r\n");
      out.write("135deg,\r\n");
      out.write("#8b5cf6,\r\n");
      out.write("#6366f1\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("display:flex;\r\n");
      out.write("\r\n");
      out.write("align-items:center;\r\n");
      out.write("\r\n");
      out.write("justify-content:center;\r\n");
      out.write("\r\n");
      out.write("font-weight:700;\r\n");
      out.write("\r\n");
      out.write("font-size:18px;\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("box-shadow:\r\n");
      out.write("0 0 20px rgba(139,92,246,0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"topbar\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"search-container\">\r\n");
      out.write("\r\n");
      out.write("    <input type=\"text\"\r\n");
      out.write("           id=\"moduleSearch\"\r\n");
      out.write("           class=\"search-box\"\r\n");
      out.write("           placeholder=\"Search modules...\"\r\n");
      out.write("           onkeyup=\"showSuggestions()\"\r\n");
      out.write("           onkeydown=\"searchModule(event)\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"suggestions-box\"\r\n");
      out.write("         id=\"suggestionsBox\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"user-section\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"user-profile\">\r\n");
      out.write("\r\n");
      out.write("            <i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("\r\n");
      out.write("            <span>\r\n");
      out.write("\r\n");
      out.write("                Admin\r\n");
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"LogoutServlet\"\r\n");
      out.write("           class=\"logout-link\">\r\n");
      out.write("\r\n");
      out.write("           Logout\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"clock\"\r\n");
      out.write("             id=\"liveClock\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"profile-circle\">\r\n");
      out.write("\r\n");
      out.write("            A\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function updateClock(){\r\n");
      out.write("\r\n");
      out.write("const now =\r\n");
      out.write("new Date();\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\r\n");
      out.write("'liveClock')\r\n");
      out.write("\r\n");
      out.write(".innerHTML =\r\n");
      out.write("\r\n");
      out.write("now.toLocaleTimeString();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("setInterval(\r\n");
      out.write("updateClock,\r\n");
      out.write("1000);\r\n");
      out.write("\r\n");
      out.write("updateClock();\r\n");
      out.write("\r\n");
      out.write("function searchModule(event){\r\n");
      out.write("\r\n");
      out.write("if(event.key === \"Enter\"){\r\n");
      out.write("\r\n");
      out.write("event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("let value =\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\r\n");
      out.write("\"moduleSearch\")\r\n");
      out.write("\r\n");
      out.write(".value.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("if(value.includes(\"dashboard\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"DashboardServlet\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(value.includes(\"patient\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"patientRegister.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(value.includes(\"doctor\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"doctorRegister.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(value.includes(\"appointment\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"appointment.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(value.includes(\"ai\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"aiAssistant.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(value.includes(\"lab\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"labReport.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else{\r\n");
      out.write("\r\n");
      out.write("alert(\r\n");
      out.write("\"Module not found!\");\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("const modules = [\r\n");
      out.write("\r\n");
      out.write("\"Dashboard\",\r\n");
      out.write("\"Patient\",\r\n");
      out.write("\"Doctor\",\r\n");
      out.write("\"Appointment\",\r\n");
      out.write("\"AI Assistant\",\r\n");
      out.write("\"Lab Report\"\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("function showSuggestions(){\r\n");
      out.write("\r\n");
      out.write("let input =\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\r\n");
      out.write("\"moduleSearch\")\r\n");
      out.write("\r\n");
      out.write(".value.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("let box =\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\r\n");
      out.write("\"suggestionsBox\");\r\n");
      out.write("\r\n");
      out.write("box.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("if(input === \"\"){\r\n");
      out.write("\r\n");
      out.write("box.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("return;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("let filtered =\r\n");
      out.write("\r\n");
      out.write("modules.filter(module =>\r\n");
      out.write("\r\n");
      out.write("module.toLowerCase()\r\n");
      out.write(".includes(input)\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("filtered.forEach(module => {\r\n");
      out.write("\r\n");
      out.write("let div =\r\n");
      out.write("\r\n");
      out.write("document.createElement(\r\n");
      out.write("\"div\");\r\n");
      out.write("\r\n");
      out.write("div.classList.add(\r\n");
      out.write("\"suggestion-item\");\r\n");
      out.write("\r\n");
      out.write("div.innerText = module;\r\n");
      out.write("\r\n");
      out.write("div.onclick = function(){\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\r\n");
      out.write("\"moduleSearch\")\r\n");
      out.write("\r\n");
      out.write(".value = module;\r\n");
      out.write("\r\n");
      out.write("box.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("redirectModule(module);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("box.appendChild(div);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("box.style.display =\r\n");
      out.write("\r\n");
      out.write("filtered.length > 0\r\n");
      out.write("? \"block\"\r\n");
      out.write(": \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function redirectModule(module){\r\n");
      out.write("\r\n");
      out.write("module = module.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("if(module.includes(\"dashboard\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"DashboardServlet\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(module.includes(\"patient\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"patientRegister.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(module.includes(\"doctor\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"doctorRegister.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(module.includes(\"appointment\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"appointment.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(module.includes(\"ai\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"aiAssistant.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("else if(module.includes(\"lab\")){\r\n");
      out.write("\r\n");
      out.write("window.location.href =\r\n");
      out.write("\"labReport.jsp\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
